### ISSUE TITLE
重启百度子页面——海关数据子页面设计

### ISSUE THREAD

**Issue by rachel11** [Tradesparq/landing#3]
hi Vivian，
请帮忙设计海关数据百度推广子页面，海关数据子页面的内容我会邮件给你！
url：http://landing.tradesparq.com/

- [ ] 海关数据 
- [ ] 社交B2B 设计排版错
- [ ] EDM代营销 涉及到案例客户隐私，需销售沟通跟进
- [ ] 金蜘蛛 销售材料未提供
- [x] 采购商报告

**Comment by rachel11** [comment]
vivian's design：

海关数据
![default](https://cloud.githubusercontent.com/assets/13618432/10661875/3742dd2e-78e3-11e5-9523-57f612de29dd.jpg)

**Comment by rachel11** [comment]
社交B2B
![b2b](https://cloud.githubusercontent.com/assets/13618432/10661947/b8c2d23c-78e3-11e5-935f-421d5b46b653.jpg)

**Comment by rachel11** [comment]
EDM代营销
![emd](https://cloud.githubusercontent.com/assets/13618432/10661965/d28c661a-78e3-11e5-9066-a60b28922340.jpg)

**Comment by rachel11** [comment]
采购商报告
![default](https://cloud.githubusercontent.com/assets/13618432/10662000/081940fa-78e4-11e5-9803-b21a3209c93e.jpg)
@chloexiaoxiao @iEricKoh @edwardrf

**Comment by rachel11** [comment]
@vivian313 
hi Vivian，采购商报告子页面缺了一张关键图：财务分析（如下图），请补上！
![image](https://cloud.githubusercontent.com/assets/13618432/10749061/388bc9ea-7ca1-11e5-9447-89d74d690f5d.png)

**Comment by vivian313** [comment]
hi rachel,
 页面添加完成，请查看！
 
------------------ Original ------------------

**Comment by rachel11** [comment]
@vivian313 hi vivian,新设计稿在哪里查看

**Comment by vivian313** [comment]
我添加在附件中了
------------------ Original ------------------

**Comment by rachel11** [comment]
似乎没有看到有附件信息啊！





rachel.chen@tradesparq.com
 
发件人： vivian313
发送时间： 2015-10-27 17:39
收件人： Tradesparq/landing
抄送： rachel
主题： Re: [landing] 重启百度子页面——海关数据子页面设计 (#3)
我添加在附件中了 
------------------ Original ------------------

**Comment by vivian313** [comment]
我在qq上面又给你发了一份。
 
------------------ Original ------------------

**Comment by rachel11** [comment]
如下图红框处sh设计需要打模糊处理
![image](https://cloud.githubusercontent.com/assets/13618432/11114304/bc410e70-895e-11e5-9c36-08d3c4d653e9.png)

**Comment by rachel11** [comment]
done
