### ISSUE TITLE
重启百度子页面——采购商报告子页面设计

### ISSUE THREAD

**Issue by rachel11** [Tradesparq/landing#4]
采购商报告
![default](https://cloud.githubusercontent.com/assets/13618432/10662000/081940fa-78e4-11e5-9803-b21a3209c93e.jpg)

**Comment by rachel11** [comment]
![default](https://cloud.githubusercontent.com/assets/13618432/10754519/29d19880-7cd3-11e5-9e88-0be939b066a1.jpg)
@chloexiaoxiao 采购商报告定稿

**Comment by rachel11** [comment]
hi Vivian，因为涉及到用户隐私，容易引起不必要的纠纷，请将以下几处信息模糊化处理。
- [ ] 采购商信息
- [ ] 采购各部门各关键职位的联系信息
- [ ] 联系人列表
- [ ] 企业财务信息
一、采购商信息
![image](https://cloud.githubusercontent.com/assets/13618432/10778124/92b897f6-7d5d-11e5-8958-bb00b63a1e7d.png)
二、采购各部门各关键职位的联系信息
![image](https://cloud.githubusercontent.com/assets/13618432/10778144/bd6ccea4-7d5d-11e5-9a55-f1599a404f18.png)
三、联系人列表
![image](https://cloud.githubusercontent.com/assets/13618432/10778161/fd21a308-7d5d-11e5-93bf-7ae49d7d2f5f.png)
四、企业财务报告
![image](https://cloud.githubusercontent.com/assets/13618432/10778187/51aae632-7d5e-11e5-9208-ecbff888caee.png)
![image](https://cloud.githubusercontent.com/assets/13618432/10778191/596ed19e-7d5e-11e5-975f-50a688a63caa.png)

**Comment by vivian313** [comment]
修改完成，发到你的qq里了，注意查看。
 
------------------ Original ------------------

**Comment by rachel11** [comment]
采购商报告定稿
![2](https://cloud.githubusercontent.com/assets/13618432/10779222/a3ab843c-7d68-11e5-943d-3a04d12e7547.jpg)
@chloexiaoxiao @edwardrf @iEricKoh

**Comment by rachel11** [comment]
done
