### ISSUE TITLE
百度推广界面上增加一个采购商报告的链接

### ISSUE THREAD

**Issue by rachel11** [Tradesparq/landing#9]
百度推广界面上增加一个采购商报告的链接。
原界面上的金蜘蛛由于销售方面和升级需要的原因，暂时不上线，eric，请暂时把金蜘蛛hide起来（升级后会再上一个金蜘蛛的子页面）。
原金蜘蛛上的链接换成采购商报告的链接，能否重新设计？
![image](https://cloud.githubusercontent.com/assets/13618432/11113982/fa04f6b6-895b-11e5-9ce3-0969c9c1167f.png)
@chloexiaoxiao

**Comment by iEricKoh** [comment]
Here's the screenshot of design, see screenshot below.
Please provide me with the content for "采购商报告" so I can update the the information, thanks.

![screenshot from 2015-11-16 15 16 27](https://cloud.githubusercontent.com/assets/8081074/11176230/f8f3c50a-8c75-11e5-80a8-e1cbb7d38000.png)

**Comment by rachel11** [comment]
采购商报告：https://github.com/Tradesparq/landing/issues/4
设计稿上次的邮件里就有：
![image](https://cloud.githubusercontent.com/assets/13618432/11176298/7ed9ec12-8c76-11e5-8da9-1ee48796144a.png)
![image](https://cloud.githubusercontent.com/assets/13618432/11176293/76c5ef76-8c76-11e5-9606-6c657f8a97eb.png)

**Comment by rachel11** [comment]
![image](https://cloud.githubusercontent.com/assets/13618432/11176325/d395fa98-8c76-11e5-9024-bee29b0bc6be.png)

**Comment by iEricKoh** [comment]
I'm not asking the content for detail page,  I guess you misunderstood my question, see highlight section in screenshot below.

![b2b](https://cloud.githubusercontent.com/assets/8081074/11176617/99c28fae-8c79-11e5-8782-b6848a50386a.png)

**Comment by rachel11** [comment]
客户长期攻克不下来？一直联系不上关键人？没关系，来找我们吧！只要给我们相关企业名称，我们可以为您提供定制化的采购商企业详细报告，精准到各个采购商企业各个岗位负责人、财务状况、企业近况，帮您解决外贸开发最后一步难题！
